name: Check Release PR

on:
  pull_request:
    paths:
      - 'CHANGELOG.md'

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  check_release_pr:
    name: Check Release PR
    if: startsWith(github.head_ref, 'chore/release/')
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout faker
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          path: faker

      - name: Checkout playground
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          repository: faker-js/playground
          path: playground

      - name: Install pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        with:
          package_json_file: faker/package.json

      - name: Set node version to 24
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 24
          cache: 'pnpm'
          cache-dependency-path: |
            faker/pnpm-lock.yaml
            playground/pnpm-lock.yaml

      - name: Install deps - faker
        run: |
          cd faker
          pnpm install

      - name: Build - faker
        run: |
          cd faker
          pnpm run build

      - name: Install deps - playground
        run: |
          cd playground
          sed -i 's/overrides-for-release/overrides/' package.json
          pnpm install --no-frozen-lockfile

      - name: Build - playground
        run: |
          cd playground
          pnpm run build

      - name: Test - playground
        run: |
          cd playground
          pnpm run test
